package com.sbnz.trud.io.model;

public enum Symptom {

	SWELLING,
	WEIGHT_GAIN,
	SEVERE_HEADACHES,
	SHORTNESS_OF_BREATH,
	SEIZURES,
	LOSS_OF_CONSIOUSNESS,
	NAUSEA,
	VOMITING,
	HIGH_BLOOD_PRESSURE,
	PROTEINURIA,
	LOW_THROMBOCYES_COUNT,
	UNUSUAL_THIRST,
	FREQUENT_URINATION,
	FATIGUE,
	BLURRY_VISION,
	ELEVATED_LIVER_ENZYMES
}
