package trud.io.kjar;
import com.sbnz.trud.io.model.OgttTest;
import com.sbnz.trud.io.model.Birth;
import com.sbnz.trud.io.model.Patient;
import com.sbnz.trud.io.model.Pregnancy;
import com.sbnz.trud.io.model.Illness;
import com.sbnz.trud.io.model.Therapy;
import com.sbnz.trud.io.model.DailyGlucoseLevel;
import com.sbnz.trud.io.service.contracts.IIllnessService;
import java.time.LocalDateTime;
import java.time.LocalDate;
import java.lang.Math;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.time.Period;
import java.util.Collections;
import java.util.ArrayList;
import java.time.*;  

global com.sbnz.trud.io.service.contracts.IIllnessService illnessService; 

/*
rule "Primary sampling > 199"
	agenda-group "ogtt"
	when
		$ogtt: OgttTest( result == "SUBMITED", primarySampling > 199 )
	then
		modify($ogtt) {
			setResult("POSITIVE");
		} 
end

rule "Primary sampling < 140"
	agenda-group "ogtt"
	when 
		$ogtt: OgttTest( result == "SUBMITED", primarySampling < 140 )
	then
		modify($ogtt) {
			setResult("NEGATIVE");
		}
end

rule "Primary sampling > 140 and < 199"
	agenda-group "ogtt"
	when 
	 	$ogtt: OgttTest( result == "SUBMITED", primarySampling > 140 && primarySampling < 199 )
	 then
	 	modify($ogtt) {
	 		setResult("EXTENDED_OGTT");
	 	}
end

rule "Extended ogtt first sample > 95"
	agenda-group "ogtt"
	when
		$ogtt: OgttTest( result == "EXTENDED_OGTT", firstBloodSampling > 95 )
	then
		modify($ogtt) {
			setResult("POSITIVE");
		}
end

rule "Extended ogtt 2. and 3. have bigger values"
	agenda-group "ogtt"
	when
		$ogtt: OgttTest( result == "EXTENDED_OGTT", secondBloodSampling > 180 && thirdBloodSampling > 155)
	then 
		modify($ogtt) {
			setResult("POSITIVE");
		}
end

rule "Extended ogtt 2. and 4. have bigger values"
	agenda-group "ogtt"
	when
		$ogtt: OgttTest( result == "EXTENDED_OGTT", secondBloodSampling > 180 && fourthBloodSampling > 140)
	then 
		modify($ogtt) {
			setResult("POSITIVE");
		}
end

rule "Extended ogtt 3. and 4. have bigger values"
	agenda-group "ogtt"
	when
		$ogtt: OgttTest( result == "EXTENDED_OGTT", thirdBloodSampling > 155 && fourthBloodSampling > 140)
	then 
		modify($ogtt) {
			setResult("POSITIVE");
		}
end

rule "Diagnose gestational diabetes"
	agenda-group "ogtt"
	when
		$ogtt: OgttTest ( result == "POSITIVE" )
		$pregnancy: Pregnancy()
		Illness(name != 'Trudnicki dijabetes') from $pregnancy.getIllnesses();
	then
		Illness diabetes = illnessService.findByName("Trudnicki dijabetes");
       	modify($pregnancy){
       		getIllnesses().add(diabetes);
       	}
end


rule "Set Therapy - week <= 35 and secondPostprandial > 126"
	agenda-group "metforminTherapy"
	when
		$pregnancy: Pregnancy( 
			$startDate: startDate, 
			Math.abs(Duration.between(LocalDate.now().atStartOfDay(), $startDate.atStartOfDay()).toDays()) <= 35*7, 
			$glucoseLevels: glucoseLevels, 
			$ogttTests: ogttTests, 
			ogttTests.size() > 0,
			illnesses.size() > 0 )
		DailyGlucoseLevel(date.equals(LocalDate.now()), ( secondPostprandial > 126 && secondPostprandial <= 162 )) from $glucoseLevels
		OgttTest( $date: date, Math.abs(Duration.between(LocalDate.now().atStartOfDay(), $date.atStartOfDay()).toDays()) > 7 ) from $ogttTests
		$patient: Patient( id ==  $pregnancy.getPatient().getId())
    	Illness( name == 'Trudnicki dijabetes' ) from $pregnancy.getIllnesses()
    	not ( Therapy( medicine == 'Metformin' ) from $patient.getTherapies() )
	then
		Therapy t = new Therapy('Metformin');
       	insert(t);
       	modify($patient){
       		getTherapies().add(t);
       	}   
end

rule "Set Therapy - week > 35 secondPostprandial > 144"
	agenda-group "metforminTherapy"
	when
		$pregnancy: Pregnancy( 
			$startDate: startDate, 
			Math.abs(Duration.between(LocalDate.now().atStartOfDay(), $startDate.atStartOfDay()).toDays()) > 35*7, 
			$glucoseLevels: glucoseLevels, 
			$ogttTests: ogttTests, 
			ogttTests.size() > 0,
			illnesses.size() > 0 )
		DailyGlucoseLevel(date.equals(LocalDate.now()), ( secondPostprandial > 144 && secondPostprandial <= 162 )) from $glucoseLevels
		OgttTest( $date: date, Math.abs(Duration.between(LocalDate.now().atStartOfDay(), $date.atStartOfDay()).toDays()) > 7 ) from $ogttTests
		$patient: Patient( id ==  $pregnancy.getPatient().getId())
    	Illness( name == 'Trudnicki dijabetes' ) from $pregnancy.getIllnesses()
    	not ( Therapy( medicine == 'Metformin' ) from $patient.getTherapies() )
	then
		Therapy t = new Therapy('Metformin');
       	insert(t);
       	modify($patient){
       		getTherapies().add(t);
       	}   
end

rule "Set Therapy - preprandial > 100"
	agenda-group "metforminTherapy"
	when
		$pregnancy: Pregnancy( $glucoseLevels: glucoseLevels, $ogttTests: ogttTests, ogttTests.size() > 0, illnesses.size() > 0 )
		DailyGlucoseLevel( date.equals(LocalDate.now()), preprandial > 100 ) from $glucoseLevels
		OgttTest( $date: date, Math.abs(Duration.between(LocalDate.now().atStartOfDay(), $date.atStartOfDay()).toDays()) > 7 ) from $ogttTests
		$patient: Patient( id ==  $pregnancy.getPatient().getId())
    	Illness( name == 'Trudnicki dijabetes' ) from $pregnancy.getIllnesses()
    	not ( Therapy( medicine == 'Metformin' ) from $patient.getTherapies() )
	then
		Therapy t = new Therapy('Metformin');
       	insert(t);
       	modify($patient){
       		getTherapies().add(t);
       	}   
end

rule "Set Therapy - firstPrepandial > 162"
	agenda-group "metforminTherapy"
	when
		$pregnancy: Pregnancy( $glucoseLevels: glucoseLevels, $ogttTests: ogttTests, ogttTests.size() > 0, illnesses.size() > 0 )
		DailyGlucoseLevel(date.equals(LocalDate.now()),  firstPostprandial > 162) from $glucoseLevels
		OgttTest($date: date, Math.abs(Duration.between(LocalDate.now().atStartOfDay(), $date.atStartOfDay()).toDays()) > 7) from $pregnancy.getOgttTests() 
		$patient: Patient( id ==  $pregnancy.getPatient().getId())
    	Illness(name == 'Trudnicki dijabetes') from $pregnancy.getIllnesses()
    	not (Therapy(medicine == 'Metformin') from $patient.getTherapies())
	then
		Therapy t = new Therapy('Metformin');
       	insert(t);
       	modify($patient){
       		getTherapies().add(t);
       	}   
end

rule "Set Therapy - secondPrepandial > 162"
	agenda-group "metforminTherapy"
	when
		$pregnancy: Pregnancy( $glucoseLevels: glucoseLevels, $ogttTests: ogttTests, ogttTests.size() > 0, illnesses.size() > 0 )
		DailyGlucoseLevel(date.equals(LocalDate.now()),  secondPostprandial > 162) from $glucoseLevels
		OgttTest($date: date, Math.abs(Duration.between(LocalDate.now().atStartOfDay(), $date.atStartOfDay()).toDays()) > 7) from $pregnancy.getOgttTests() 
		$patient: Patient( id ==  $pregnancy.getPatient().getId())
    	Illness(name == 'Trudnicki dijabetes') from $pregnancy.getIllnesses()
    	not (Therapy(medicine == 'Metformin') from $patient.getTherapies())
	then
		Therapy t = new Therapy('Metformin');
       	insert(t);
       	modify($patient){
       		getTherapies().add(t);
       	}   
end

rule "Ogtt in 12 week of pregnancy - births"
	agenda-group "ogttTest"
	when
		$pregnancy: Pregnancy(Math.floor(Math.abs(Duration.between(LocalDate.now().atStartOfDay(), startDate.atStartOfDay()).toDays())/7) == 12)
		$ogtt: List(size == 0) from accumulate(OgttTest(result == "NOT-PROCESSED") from $pregnancy.ogttTests; collectList())
		$pregnancies: Pregnancy($pregnancy.patient.id == patient.id, birth != null)
		$births: List(size > 0) from accumulate(Pregnancy(birth.weight > 4, $birth: birth) from $pregnancies;
									collectList($birth))
	then
		OgttTest test = new OgttTest("NOT-PROCESSED");
		modify($pregnancy) {
			getOgttTests().add(test);
		}
end

rule "Ogtt in 12 week of pregnancy - obesity"
	agenda-group "ogttTest"
	when
		$pregnancy: Pregnancy(Math.floor(Math.abs(Duration.between(LocalDate.now().atStartOfDay(), startDate.atStartOfDay()).toDays())/7) == 12,
								patient.weight/((patient.height/100)*(patient.height/100)) > 29.9)
		$ogtt: List(size == 0) from accumulate(OgttTest(result == "NOT-PROCESSED") from $pregnancy.ogttTests; collectList())
	then
		OgttTest test = new OgttTest("NOT-PROCESSED");
		modify($pregnancy) {
			getOgttTests().add(test);
		}
end

rule "Ogtt in 12 week of pregnancy - age > 35"
	agenda-group "ogttTest"
	when
		$pregnancy: Pregnancy(Math.floor(Math.abs(Duration.between(LocalDate.now().atStartOfDay(), startDate.atStartOfDay()).toDays())/7) == 12,
								(LocalDateTime.now().getYear() - patient.dateOfBirth.getYear()) > 35)
		$ogtt: List(size == 0) from accumulate(OgttTest(result == "NOT-PROCESSED") from $pregnancy.ogttTests; collectList())
	then
		OgttTest test = new OgttTest("NOT-PROCESSED");
		modify($pregnancy) {
			getOgttTests().add(test);
		}
end
*/