package trud.io.kjar;
import com.sbnz.trud.io.model.Pregnancy;
import com.sbnz.trud.io.model.Symptom;
import com.sbnz.trud.io.model.Therapy;
import com.sbnz.trud.io.model.Illness;
import java.util.Collection;
import java.time.LocalDate;

rule "Premature labor - vomiting"
	no-loop
	agenda-group "prematureLabor"
    when
     	$pregnancy: Pregnancy(symptoms.size > 0, birth == null,  $date: startDate, LocalDate.now().isBefore($date.plusWeeks(37)))
        $s: Symptom(this == Symptom.VOMITING) from $pregnancy.getSymptoms()
       
    then
        modify($pregnancy) {
        	setPrematureLabor(true);
        }
end

rule "Premature labor - pressure in lower belly"
	no-loop
	agenda-group "prematureLabor"
    when
     	$pregnancy: Pregnancy(symptoms.size > 0, birth == null, $date: startDate, LocalDate.now().isBefore($date.plusWeeks(37)))
        $s: Symptom(this == Symptom.PRESSURE_IN_LOWER_BELLY) from $pregnancy.getSymptoms()
       
    then
        modify($pregnancy) {
        	setPrematureLabor(true);
        }
end

rule "Premature labor - dull backache"
	no-loop
	agenda-group "prematureLabor"
    when
     	$pregnancy: Pregnancy(symptoms.size > 0, birth == null, $date: startDate, LocalDate.now().isBefore($date.plusWeeks(37)))
        $s: Symptom(this == Symptom.DULL_BACKACHE) from $pregnancy.getSymptoms()
       
    then
        modify($pregnancy) {
        	setPrematureLabor(true);
        }
end

rule "Premature labor - therapy corticosteroids"
	no-loop
	agenda-group "prematureLabor"
    when
     	$pregnancy: Pregnancy(prematureLabor == true, birth == null,  $date: startDate, LocalDate.now().isBefore($date.plusWeeks(34)) && LocalDate.now().isAfter($date.plusWeeks(23)))
    then
    	Therapy t = new Therapy('Kortikosteroidi');
       	insert(t);
       	modify($pregnancy.getPatient()){
       		getTherapies().add(t);
       	}   
end

rule "Premature labor - therapy tocolytics"
	no-loop
	agenda-group "prematureLabor"
    when
     	$pregnancy: Pregnancy(prematureLabor == true, birth == null, $date: startDate, illnesses.size > 0 ,LocalDate.now().isBefore($date.plusWeeks(34)) && LocalDate.now().isAfter($date.plusWeeks(23)))
    	$illness: Illness(name != 'Preeklampsija' && name != 'Eklampsija' ) from $pregnancy.getIllnesses();
    	
    then
    	Therapy t = new Therapy('Tokolitici');
       	insert(t);
       	modify($pregnancy.getPatient()){
       		getTherapies().add(t);
       	}   
end

