package trud.io.kjar;
import com.sbnz.trud.io.model.Pregnancy;
import com.sbnz.trud.io.model.DoubleTest;
import com.sbnz.trud.io.model.TripleTest;
import com.sbnz.trud.io.model.QuadripleTest;
import com.sbnz.trud.io.model.Amniocentesis;
import java.time.LocalDate;
import java.lang.Math;
import java.time.temporal.ChronoUnit;
import java.time.Period;
rule "Double test - trisomy21 Screen positive"
agenda-group "doubleTest"
when
	$pregnancy: Pregnancy(birth == null, doubleTest != null)
    $d: DoubleTest(result == 'Calculate risks', resultT21 == null , trisomy21 <  290) from $pregnancy.getDoubleTest()
then
 	 modify($d) {
        	setResultT21("Screen positive");
        }
end
rule "Double test - trisomy18 Screen positive"
agenda-group "doubleTest"
when
	$pregnancy: Pregnancy(birth == null, doubleTest != null)
    $d: DoubleTest(result == 'Calculate risks', resultT18 == null,  trisomy18 <  110) from $pregnancy.getDoubleTest()
then
 	 modify($d) {
        	setResultT18("Screen positive");
        }
end
rule "Double test - trisomy13 Screen positive"
agenda-group "doubleTest"
when
	$pregnancy: Pregnancy(birth == null, doubleTest != null)
    $d: DoubleTest(result == 'Calculate risks', resultT13 == null , trisomy13 <  100) from $pregnancy.getDoubleTest()
then
 	 modify($d) {
        	setResultT13("Screen positive");
        }
end
rule "Triple test - trisomy21 Screen positive"
agenda-group "tripleTest"
when
	$pregnancy: Pregnancy(birth == null, tripleTest != null)
    $t: TripleTest(result == 'Calculate risks', resultT21 == null , trisomy21 <  290) from $pregnancy.getTripleTest()
then
 	 modify($t) {
        	setResultT21("Screen positive");
        }
end
rule "Triple test - trisomy18 Screen positive"
agenda-group "tripleTest"
when
	$pregnancy: Pregnancy(birth == null, tripleTest != null)
    $t: TripleTest(result == 'Calculate risks', resultT18 == null, trisomy18 <  110) from $pregnancy.getTripleTest()
then
 	 modify($t) {
        	setResultT18("Screen positive");
        }
end
rule "Triple test - trisomy13 Screen positive"
agenda-group "tripleTest"
when
	$pregnancy: Pregnancy(birth == null, tripleTest != null)
    $t: TripleTest(result == 'Calculate risks', resultT13 == null, trisomy13 <  100) from $pregnancy.getTripleTest()
then
 	 modify($t) {
        	setResultT13("Screen positive");
        }
end
rule "Quadriple test - trisomy21 Screen positive"
agenda-group "quadripleTest"
when
	$pregnancy: Pregnancy(birth == null, quadripleTest != null)
    $q: QuadripleTest(result == 'Calculate risks', resultT21 == null,  trisomy21 <  290) from $pregnancy.getQuadripleTest()
then
 	 modify($q) {
        	setResultT21("Screen positive");
        }
end
rule "Quadriple test - trisomy18 Screen positive"
agenda-group "quadripleTest"
when
	$pregnancy: Pregnancy(birth == null, quadripleTest != null)
    $q: QuadripleTest(result == 'Calculate risks',  resultT18 == null ,trisomy18 <  110) from $pregnancy.getQuadripleTest()
then
 	 modify($q) {
        	setResultT18("Screen positive");
        }
end
rule "Quadriple test - trisomy13 Screen positive"
agenda-group "quadripleTest"
when
	$pregnancy: Pregnancy(birth == null, quadripleTest != null)
    $q: QuadripleTest(result == 'Calculate risks', resultT13 == null, trisomy13 <  100) from $pregnancy.getQuadripleTest()
then
 	 modify($q) {
        	setResultT13("Screen positive");
        }
end
rule "Amniocentesis - trisomy21 Screen positive"
agenda-group "amniocentesis"
when
	$pregnancy: Pregnancy(birth == null, amniocentesis != null)
    $a: Amniocentesis(result == 'Calculate risks', resultT21 == null, trisomy21 <  290) from $pregnancy.getAmniocentesis()
then
 	 modify($a) {
        	setResultT21("Screen positive");
        }
end
rule "Amniocentesis- trisomy18 Screen positive"
agenda-group "amniocentesis"
when
	$pregnancy: Pregnancy(birth == null, amniocentesis != null)
    $a: Amniocentesis(result == 'Calculate risks', resultT18 == null, trisomy18 <  110) from $pregnancy.getAmniocentesis()
then
 	 modify($a) {
        	setResultT18("Screen positive");
        }
end
rule "Amniocentesis - trisomy13 Screen positive"
agenda-group "amniocentesis"
when
	$pregnancy: Pregnancy(birth == null, amniocentesis != null)
    $a: Amniocentesis(result == 'Calculate risks', resultT13 == null, trisomy13 <  100) from $pregnancy.getAmniocentesis()
then
 	 modify($a) {
        	setResultT13("Screen positive");
        }
end

rule "Double test - trisomy21 Screen negative"
agenda-group "doubleTest"
when
	$pregnancy: Pregnancy(birth == null, doubleTest != null)
    $d: DoubleTest(result == 'Calculate risks', resultT21 == null , trisomy21 >  290) from $pregnancy.getDoubleTest()
then
 	 modify($d) {
        	setResultT21("Screen negative");
        }
end
rule "Double test - trisomy18 Screen negative"
agenda-group "doubleTest"
when
	$pregnancy: Pregnancy(birth == null, doubleTest != null)
    $d: DoubleTest(result == 'Calculate risks', resultT18 == null,  trisomy18 >  110) from $pregnancy.getDoubleTest()
then
 	 modify($d) {
        	setResultT18("Screen negative");
        }
end
rule "Double test - trisomy13 Screen negative"
agenda-group "doubleTest"
when
	$pregnancy: Pregnancy(birth == null, doubleTest != null)
    $d: DoubleTest(result == 'Calculate risks', resultT13 == null , trisomy13 >  100) from $pregnancy.getDoubleTest()
then
 	 modify($d) {
        	setResultT13("Screen negative");
        }
end
rule "Triple test - trisomy21 Screen negative"
agenda-group "tripleTest"
when
	$pregnancy: Pregnancy(birth == null, tripleTest != null)
    $t: TripleTest(result == 'Calculate risks', resultT21 == null , trisomy21 >  290) from $pregnancy.getTripleTest()
then
 	 modify($t) {
        	setResultT21("Screen negative");
        }
end
rule "Triple test - trisomy18 Screen negative"
agenda-group "tripleTest"
when
	$pregnancy: Pregnancy(birth == null, tripleTest != null)
    $t: TripleTest(result == 'Calculate risks', resultT18 == null, trisomy18 >  110) from $pregnancy.getTripleTest()
then
 	 modify($t) {
        	setResultT18("Screen negative");
        }
end
rule "Triple test - trisomy13 Screen negative"
agenda-group "tripleTest"
when
	$pregnancy: Pregnancy(birth == null, tripleTest != null)
    $t: TripleTest(result == 'Calculate risks', resultT13 == null, trisomy13 >  100) from $pregnancy.getTripleTest()
then
 	 modify($t) {
        	setResultT13("Screen negative");
        }
end
rule "Quadriple test - trisomy21 Screen negative"
agenda-group "quadripleTest"
when
	$pregnancy: Pregnancy(birth == null, quadripleTest != null)
    $q: QuadripleTest(result == 'Calculate risks', resultT21 == null,  trisomy21 >  290) from $pregnancy.getQuadripleTest()
then
 	 modify($q) {
        	setResultT21("Screen negative");
        }
end
rule "Quadriple test - trisomy18 Screen negative"
agenda-group "quadripleTest"
when
	$pregnancy: Pregnancy(birth == null, quadripleTest != null)
    $q: QuadripleTest(result == 'Calculate risks',  resultT18 == null ,trisomy18 >  110) from $pregnancy.getQuadripleTest()
then
 	 modify($q) {
        	setResultT18("Screen negative");
        }
end
rule "Quadriple test - trisomy13 Screen negative"
agenda-group "quadripleTest"
when
	$pregnancy: Pregnancy(birth == null, quadripleTest != null)
    $q: QuadripleTest(result == 'Calculate risks', resultT13 == null, trisomy13 >  100) from $pregnancy.getQuadripleTest()
then
 	 modify($q) {
        	setResultT13("Screen negative");
        }
end
rule "Amniocentesis - trisomy21 Screen negative"
agenda-group "amniocentesis"
when
	$pregnancy: Pregnancy(birth == null, amniocentesis != null)
    $a: Amniocentesis(result == 'Calculate risks', resultT21 == null, trisomy21 >  290) from $pregnancy.getAmniocentesis()
then
 	 modify($a) {
        	setResultT21("Screen negative");
        }
end
rule "Amniocentesis- trisomy18 Screen negative"
agenda-group "amniocentesis"
when
	$pregnancy: Pregnancy(birth == null, amniocentesis != null)
    $a: Amniocentesis(result == 'Calculate risks', resultT18 == null, trisomy18 >  110) from $pregnancy.getAmniocentesis()
then
 	 modify($a) {
        	setResultT18("Screen negative");
        }
end
rule "Amniocentesis - trisomy13 Screen negative"
agenda-group "amniocentesis"
when
	$pregnancy: Pregnancy(birth == null, amniocentesis != null)
    $a: Amniocentesis(result == 'Calculate risks', resultT13 == null, trisomy13 >  100) from $pregnancy.getAmniocentesis()
then
 	 modify($a) {
        	setResultT13("Screen negative");
        }
end


