package trud.io.kjar;
import com.sbnz.trud.io.model.Pregnancy;
import com.sbnz.trud.io.model.TripleTest;
import com.sbnz.trud.io.model.AgeRisk;
import com.sbnz.trud.io.model.WeeklyParameters;
import java.util.Collection;
import java.time.LocalDate;
import java.lang.Math;
import java.time.temporal.ChronoUnit;
import java.time.Period;

rule "Triple test - trisomy risks"
	no-loop
	agenda-group "tripleTest"
    when
     	$pregnancy: Pregnancy(birth == null,  Math.floor(Math.abs(Duration.between(LocalDate.now().atStartOfDay(), startDate.atStartOfDay()).toDays())/7) >= 15 &&
     	Math.floor(Math.abs(Duration.between(LocalDate.now().atStartOfDay(), startDate.atStartOfDay()).toDays())/7) <= 16)
        $week: Number() from $pregnancy.getWeek()
        $patientAge: Number() from LocalDateTime.now().getYear() - $pregnancy.getPatient().dateOfBirth.getYear()
        $t: TripleTest(result == 'Not yet processed') from $pregnancy.getTripleTest()
        $age: Number() from $t.checkAge($patientAge)
       	$riskAgeT21: AgeRisk(age == $age, trisomy == 'Trisomy21' )
       	$riskAgeT18: AgeRisk(age == $age, trisomy == 'Trisomy18' )
       	$riskAgeT13: AgeRisk(age == $age, trisomy == 'Trisomy13' )
       	
        $weeklyParameters: WeeklyParameters(week == $week)
        
      	$coefAFP: Double() from $t.getCoefAfp($weeklyParameters.getMedianAfp())
      	$coefUe3: Double() from $t.getCoefUe3($weeklyParameters.getMedianUe3())
        $coefHCG: Double() from $t.getCoefHCG($weeklyParameters.getMedianHcg())
        $coefSmoker: Double() from $t.getCoefSmoker($pregnancy.getPatient().isSmoker())
        
        $risk : Double() from 1.053 * 1.24 * 2.03 *  $coefAFP * $coefUe3 * $coefHCG * $coefSmoker
        $riskT21: Double() from $riskAgeT21.getRisk() * $risk
        $riskT18: Double() from $riskAgeT18.getRisk() * $risk
        $riskT13: Double() from $riskAgeT13.getRisk() * $risk
        
    then
        modify($t) {
        	setTrisomy21($riskT21),
        	setTrisomy18($riskT18),
        	setTrisomy13($riskT13),
        	setResult('Calculate risks');
        }
end

rule "Triple test - screen negative "
	agenda-group "tripleTest"
    when
     	$pregnancy: Pregnancy(birth == null,  Math.floor(Math.abs(Duration.between(LocalDate.now().atStartOfDay(), startDate.atStartOfDay()).toDays())/7) >= 15 &&
     	Math.floor(Math.abs(Duration.between(LocalDate.now().atStartOfDay(), startDate.atStartOfDay()).toDays())/7) <= 16)
        $t: TripleTest(result == 'Calculate risks') from $pregnancy.getTripleTest()
        
         eval($t.getTrisomy21() > 270 && $t.getTrisomy13() > 150 && $t.getTrisomy18() > 150)
    then
        modify($t) {
        	setResult('Screen negative');
        }
end

rule "Triple test - screen positive "
	agenda-group "tripleTest"
    when
     	$pregnancy: Pregnancy(birth == null,  Math.floor(Math.abs(Duration.between(LocalDate.now().atStartOfDay(), startDate.atStartOfDay()).toDays())/7) >= 15 &&
     	Math.floor(Math.abs(Duration.between(LocalDate.now().atStartOfDay(), startDate.atStartOfDay()).toDays())/7) <= 16)
        $age: Number() from LocalDateTime.now().getYear() - $pregnancy.getPatient().dateOfBirth.getYear()
        $t: TripleTest(result == 'Calculate risks') from $pregnancy.getTripleTest()
        
       eval($t.getTrisomy21() < 270 || $t.getTrisomy13() < 150 || $t.getTrisomy18() < 150)
    then
        modify($t) {
        	setResult('Screen positive');
        	//ukoliko su rezultati losi i ima genetske anomalije onda se salje na amniocentezu
        	//ukoliko su rezultati losi i trudnoca je zaceta vantelesnom oplodnjom ide na prenatalni
        	//ukoliko su rezultati samo losi onda bira amniocentezu ili prenatalni
        }
end

